# code to create the json prediction:
webApi = 'https://awsagunva1011.jnj.com:8443/WebAPI'

populationSettings <- list(PatientLevelPrediction::createStudyPopulationSettings(riskWindowEnd = 30,
                                                                                 riskWindowStart = 1,
                                                                                 washoutPeriod = 365,
                                                                                 removeSubjectsWithPriorOutcome = TRUE,
                                                                                 firstExposureOnly = TRUE,
                                                                                 priorOutcomeLookback = 99999,
                                                                                 requireTimeAtRisk = FALSE),
                           PatientLevelPrediction::createStudyPopulationSettings(riskWindowEnd = 60,
                                                                                 riskWindowStart = 1,
                                                                                 washoutPeriod = 365,
                                                                                 removeSubjectsWithPriorOutcome = TRUE,
                                                                                 firstExposureOnly = TRUE,
                                                                                 priorOutcomeLookback = 99999,
                                                                                 requireTimeAtRisk = FALSE),
                           PatientLevelPrediction::createStudyPopulationSettings(riskWindowEnd = 90,
                                                                                 riskWindowStart = 1,
                                                                                 washoutPeriod = 365,
                                                                                 removeSubjectsWithPriorOutcome = TRUE,
                                                                                 firstExposureOnly = TRUE,
                                                                                 priorOutcomeLookback = 99999,
                                                                                 requireTimeAtRisk = FALSE))


modelList <- list(list("LassoLogisticRegressionSettings" = list("variance" = 0.01)))

covariateSettings <- list(list(list(fnct = 'createCovariateSettings',
                                    settings = FeatureExtraction::createCovariateSettings(useDemographicsGender = T,
                                                                                          useDemographicsEthnicity = T,
                                                                                          useDemographicsRace = T,
                                                                                          longTermStartDays = -365,
                                                                                          endDays = 0,
                                                                                          useConditionGroupEraLongTerm = T,
                                                                                          useDrugGroupEraLongTerm = T,
                                                                                          useProcedureOccurrenceLongTerm = T,
                                                                                          useDeviceExposureLongTerm = T,
                                                                                          useObservationLongTerm = T,
                                                                                          useMeasurementLongTerm = T)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age <20',
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x<20] <- 1; return(result)}',
                                                    covariateId = 14580020,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 20-44', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=20 & x<=44] <- 1; return(result)}',
                                                    covariateId = 14582044, # x = covariate data vector, filter with dplyr 
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 45-54', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=45 & x<=54] <- 1; return(result)}',
                                                    covariateId = 14584554,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 55-64', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=55 & x<=64] <- 1; return(result)}',
                                                    covariateId = 14585564,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 65-74', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=65 & x<=74] <- 1; return(result)}',
                                                    covariateId = 14586574,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 75-84', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=75 & x<=84] <- 1; return(result)}',
                                                    covariateId = 14587584,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age >84', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>84] <- 1; return(result)}',
                                                    covariateId = 14588500,
                                                    analysisId = 458)))
)

resrictOutcomePops <- NULL
resrictModelCovs <- NULL

executionSettings <- list(minCovariateFraction = 0.000,
                          normalizeData = T,
                          testSplit = "stratified",
                          testFraction = 0.20,
                          splitSeed = 1000,
                          nfold = 3)

json <- createDevelopmentStudyJson(packageName = 'CovCoagFullPrediction',
                           packageDescription = 'Prediction model based on full predictor set.',
                           createdBy = 'Henrik John',
                           organizationName = 'Erasmus University Medical Center',
                           targets = data.frame(targetId = c(22932),
                                                cohortId = c(22932),
                                                targetName = c('COVID19 PCR positive test or diagnosis')),
                           outcomes = data.frame(outcomeId = c(22601,22600,22599,22595,22596,22602,22933),
                                                 cohortId = c(22601,22600, 22599,22595,22596,22602,22933),
                                                 outcomeName = c('MI','IS','MI_and_IS','PE','DVT_narrow',
                                                                 'VTE_narrow', 'DTH')),
                           populationSettings = populationSettings,
                           modelList = modelList,
                           covariateSettings = covariateSettings,
                           resrictOutcomePops = resrictOutcomePops,
                           resrictModelCovs = resrictModelCovs,
                           executionSettings = executionSettings,
                           webApi = webApi,
                           outputLocation = 'D:/hjohn/CovCoagFull',
                           jsonName = 'predictionAnalysisList.json')

specifications <- Hydra::loadSpecifications(file.path('D:/hjohn/CovCoagFull', 'predictionAnalysisList.json'))
Hydra::hydrate(specifications = specifications, outputFolder = 'D:/hjohn/CovCoagFull/CovCoagFullPrediction')
