# code to create the json prediction:

populationSettings <- list(PatientLevelPrediction::createStudyPopulationSettings(riskWindowEnd = 30,
                                                                                 riskWindowStart = 1,
                                                                                 washoutPeriod = 365,
                                                                                 removeSubjectsWithPriorOutcome = TRUE,
                                                                                 firstExposureOnly = TRUE,
                                                                                 priorOutcomeLookback = 99999,
                                                                                 requireTimeAtRisk = FALSE),
                           PatientLevelPrediction::createStudyPopulationSettings(riskWindowEnd = 60,
                                                                                 riskWindowStart = 1,
                                                                                 washoutPeriod = 365,
                                                                                 removeSubjectsWithPriorOutcome = TRUE,
                                                                                 firstExposureOnly = TRUE,
                                                                                 priorOutcomeLookback = 99999,
                                                                                 requireTimeAtRisk = FALSE),
                           PatientLevelPrediction::createStudyPopulationSettings(riskWindowEnd = 90,
                                                                                 riskWindowStart = 1,
                                                                                 washoutPeriod = 365,
                                                                                 removeSubjectsWithPriorOutcome = TRUE,
                                                                                 firstExposureOnly = TRUE,
                                                                                 priorOutcomeLookback = 99999,
                                                                                 requireTimeAtRisk = FALSE))


modelList <- list(list("LassoLogisticRegressionSettings" = list("variance" = 0.01)))

covariateSettings <- list(list(list(fnct = 'createCovariateSettings',
                                    settings = FeatureExtraction::createCovariateSettings(useDemographicsGender = T,
                                                                                          longTermStartDays = -183,
                                                                                          endDays = -4,
                                                                                          useDrugGroupEraLongTerm = T)),
                               list(fnct = 'createCovariateSettings',
                                    settings = FeatureExtraction::createCovariateSettings(useConditionGroupEraAnyTimePrior = T,
                                                                                          endDays = 0)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age below 20',
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x<20] <- 1; return(result)}',
                                                    covariateId = 14580019,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 20-29', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=20 & x<=29] <- 1; return(result)}',
                                                    covariateId = 14582029, # x = covariate data vector, filter with dplyr 
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 30-39', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=30 & x<=39] <- 1; return(result)}',
                                                    covariateId = 14583039,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 40-49', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=40 & x<=49] <- 1; return(result)}',
                                                    covariateId = 14584049,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 50-59', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=50 & x<=59] <- 1; return(result)}',
                                                    covariateId = 14585059,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 60-69', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=60 & x<=69] <- 1; return(result)}',
                                                    covariateId = 14586069,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 70-79', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=70 & x<=79] <- 1; return(result)}',
                                                    covariateId = 14587079,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 80 and above', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=80] <- 1; return(result)}',
                                                    covariateId = 14588000,
                                                    analysisId = 458))),
                          list(list(fnct = 'createCovariateSettings',
                                    settings = FeatureExtraction::createCovariateSettings(useDemographicsGender = T,
                                                                                          useDemographicsEthnicity = T,
                                                                                          useDemographicsRace = T,
                                                                                          longTermStartDays = -365,
                                                                                          endDays = 0,
                                                                                          useConditionGroupEraLongTerm = T,
                                                                                          useDrugGroupEraLongTerm = T,
                                                                                          useProcedureOccurrenceLongTerm = T,
                                                                                          useDeviceExposureLongTerm = T,
                                                                                          useObservationLongTerm = T,
                                                                                          useMeasurementLongTerm = T)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age below 20',
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x<20] <- 1; return(result)}',
                                                    covariateId = 14580019,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 20-29', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=20 & x<=29] <- 1; return(result)}',
                                                    covariateId = 14582029, # x = covariate data vector, filter with dplyr 
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 30-39', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=30 & x<=39] <- 1; return(result)}',
                                                    covariateId = 14583039,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 40-49', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=40 & x<=49] <- 1; return(result)}',
                                                    covariateId = 14584049,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 50-59', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=50 & x<=59] <- 1; return(result)}',
                                                    covariateId = 14585059,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 60-69', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=60 & x<=69] <- 1; return(result)}',
                                                    covariateId = 14586069,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 70-79', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=70 & x<=79] <- 1; return(result)}',
                                                    covariateId = 14587079,
                                                    analysisId = 458)),
                               list(fnct = 'createAgeCovariateSettings',
                                    settings = list(covariateName = 'Age 80 and above', 
                                                    ageMap = 'function(x){result <- rep(0, length(x)); result[x>=80] <- 1; return(result)}',
                                                    covariateId = 14588000,
                                                    analysisId = 458)))
)

resrictOutcomePops <- NULL
resrictModelCovs <- NULL

executionSettings <- list(minCovariateFraction = 0.000,
                          normalizeData = T,
                          testSplit = "stratified",
                          testFraction = 0.20,
                          splitSeed = 1000,
                          nfold = 3)

json <- createDevelopmentStudyJson(packageName = 'CovCoagFullPrediction',
                                   packageDescription = 'Prediction model based on full predictor set.',
                                   createdBy = 'Henrik John',
                                   organizationName = 'Erasmus University Medical Center',
                                   targets = data.frame(targetId = c(22932, 22956),
                                                        cohortId = c(22932, 22956),
                                                        targetName = c('COVID19 PCR positive test or diagnosis',
                                                                       'Unvaccinated COVID19 PCR positive test or diagnosis')),
                                   outcomes = data.frame(outcomeId = c(22601,22600,22599,22595,22596,22602,22933,22954),
                                                         cohortId = c(22601,22600, 22599,22595,22596,22602,22933,22954),
                                                         outcomeName = c('MI','IS','MI and IS','PE','DVT narrow',
                                                                         'VTE narrow', 'DTH', 'STR')),
                                   populationSettings = populationSettings,
                                   modelList = modelList,
                                   covariateSettings = covariateSettings,
                                   resrictOutcomePops = resrictOutcomePops,
                                   resrictModelCovs = resrictModelCovs,
                                   executionSettings = executionSettings,
                                   webApi = webApi,
                                   outputLocation = 'D:/hjohn/CovCoagFull',
                                   jsonName = 'predictionAnalysisList.json')

specifications <- Hydra::loadSpecifications(file.path('D:/hjohn/CovCoagFull', 'predictionAnalysisList.json'))
Hydra::hydrate(specifications = specifications, outputFolder = 'D:/hjohn/CovCoagFull/CovCoagFullPrediction')
